/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class src_Jeu */

#ifndef _Included_src_Jeu
#define _Included_src_Jeu
#ifdef __cplusplus
extern "C" {
#endif
#undef src_Jeu_TAILLE_GRAPHE_DEFAUT
#define src_Jeu_TAILLE_GRAPHE_DEFAUT 11L
/*
 * Class:     src_Jeu
 * Method:    initialiserJeu
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_src_Jeu_initialiserJeu
  (JNIEnv *, jclass, jint);

/*
 * Class:     src_Jeu
 * Method:    finJeu
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_src_Jeu_finJeu
  (JNIEnv *, jclass);

/*
 * Class:     src_Jeu
 * Method:    getCaseGraphe
 * Signature: (II)C
 */
JNIEXPORT jchar JNICALL Java_src_Jeu_getCaseGraphe
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     src_Jeu
 * Method:    setCaseGraphe
 * Signature: (IIC)V
 */
JNIEXPORT void JNICALL Java_src_Jeu_setCaseGraphe
  (JNIEnv *, jclass, jint, jint, jchar);

/*
 * Class:     src_Jeu
 * Method:    estFini
 * Signature: (C)Z
 */
JNIEXPORT jboolean JNICALL Java_src_Jeu_estFini
  (JNIEnv *, jclass, jchar);

#ifdef __cplusplus
}
#endif
#endif
